BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO people (user_id, first_name, last_name, email, is_available_weekdays, is_available_weekends, volunteering_interest, is_approved, token)
	VALUES (1, 'John', 'Smith', 'JohnSmith@volunteer.com', false, true, null, true, 'ride1');
INSERT INTO people (user_id, first_name, last_name, email, is_available_weekdays, is_available_weekends, volunteering_interest, is_approved, token)
	VALUES (2, 'Jane', 'Doe', 'JaneTheAdmin@boss.com', true, true, 'I love animals and cannot wait to make a difference in the world!', true, 'ride2');
INSERT INTO people (user_id, first_name, last_name, email, is_available_weekdays, is_available_weekends, volunteering_interest, is_approved, token)
	VALUES (2, 'Rowan', 'Been', 'mbeeen@gmail.com', true, false, 'I am Mr. Been, and I would love to volunteer at your animal shelter. My quiet lifestyle and love for animals make me an excellent candidate for providing company and joy to pets in need. I am not much of a talker, but I excel in non-verbal communication, which seems just right for your furry friends. Plus, my daily life is filled with humorous antics that could keep the animals entertained. I look forward to bringing smiles and receiving wagging tails in return.', null, 'ride3');

INSERT INTO species (name) VALUES ('cat');
INSERT INTO species (name) VALUES ('dog');
INSERT INTO species (name) VALUES ('bunny');

INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (1, 'Cat2.JPG', 'Pippin', 3, false, 'orange, white', 'house cat', 'S', 'Male', true, false, 'Meet Pippin, a charming and playful male cat with a striking ginger coat and mesmerizing emerald eyes. Pippin has an unusual penchant for nibbling on curtains, a habit that adds a touch of humor to his already endearing personality. While he may occasionally leave a curtain slightly frayed, his antics are sure to bring laughter and joy to any home. This quirky trait makes him uniquely special and a delightful companion to have around. If you are looking for a lovable and slightly mischievous feline friend, Pippin could be the perfect addition to your family. Embrace his curtain-eating quirks and give him the loving forever home he deserves!');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (1, 'Cat1.JPG', 'Dori', 3, false, 'orange', 'house cat', 'S', 'Female', true, false, 'Introducing Dori, a delightful female orange cat with a vibrant personality and a love for fun! Dori has a special fascination with plastic spirals, which she joyfully chases and bats around with her agile paws. Her bright orange coat shines as she leaps and twirls after her favorite toys, bringing energy and cheer to any room she graces. This playful behavior not only shows her spirited nature but also her healthy, active lifestyle. Dori is looking for a forever home where she can share her boundless joy and playfulness. If you are ready for a lively and loving companion who will keep you entertained with her adorable antics, Dori is the perfect match for you!');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (1, 'Cat3.JPG', 'Callie', 8, true, 'black', 'stray', 'XS', 'Female', false, true, 'This stray stumbled in and never left.');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (2, 'Dog1.JPG', 'Enzo', 3, false, 'cream, white', 'german shepherd', 'M', 'Male', true, true, 'Sweet boy that loves to be loved!');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (2, 'Dog2.JPG', 'Ziggy', 13, true, 'brown, blonde', 'puli', 'M', 'Male', false, false, 'Meet Ziggy, a delightful male dog with a quirky and endearing set of hobbies that make him a unique companion. Known affectionately as the "sniffervisor," Ziggy has a special talent for inspecting presents with his nose during holidays, adding a touch of excitement and curiosity to festive occasions. Not only does he love to explore through scent, but he also has a penchant for chewing zippers, a habit that showcases his playful side. His glossy coat and bright, eager eyes mirror his lively personality. He’s looking for a forever home that appreciates his special skills and provides him with plenty of love and engaging activities. If you’re ready for a fun-loving and charming canine to join your family, Ziggy is ready to bring joy and sniffervision to your life!');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (2, 'Dog3.JPG', 'Toddy', 6, true, 'black, brown', 'cattle dog mix', 'M', 'Female', true, false, 'Meet Toddy, a charming female dog with a mischievous streak and a big appetite! This lovable girl has a knack for stealthily swiping snacks, which only adds to her endearing personality. Her playful food heists are a sign of her cleverness and zest for life, making her a fun and engaging companion. Her glossy coat and bright eyes reflect her spirited nature, promising companionship and lively adventures. Toddy is looking for a family that can match her enthusiasm and perhaps keep an extra eye on their plates! If you are ready to share your heart (and maybe your snacks) with a joyful and loving canine, Toddy would love to become part of your family.');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (3, 'Rabbit1.JPG', 'Arwin', 2, false, 'grey', 'angora', 'S', 'Female', false, true, 'You have to watch her as she likes to bite ankles.');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (3, 'Rabbit2.JPG', 'Carrots', 5, false, 'brown', 'lionhead', 'XS', 'Female', false, false, 'Say hello to Carrots, a delightful female rabbit known for her gentle demeanor and charming personality. With her soft, fluffy coat and bright, curious eyes, Carrots captures the hearts of everyone she meets. This sweet bunny loves to hop around her play area, exploring every nook and cranny with enthusiasm. Carrots has a particular fondness for her namesake vegetable, and watching her nibble on a fresh carrot is a joy in itself. She is looking for a loving home where she can receive plenty of cuddles and care. If you are seeking a furry friend who will bring warmth and quiet companionship to your home, Carrots is the perfect addition to your family.');
INSERT INTO pets (species_id, main_photo, name, age, has_special_needs, color, breed, size, gender, is_fixed, is_adopted, description) 
	VALUES (3, 'Rabbit3.JPG', 'Sir Hops-A-Lot', 1, true, 'blonde', 'mini lop', 'L', 'Male', true, false, 'Meet Sir Hops-A-Lot, a charismatic male rabbit with a lively spirit and a name that truly suits his bouncy nature. Despite being blind, this adorable bunny is full of energy and loves to leap and play, adapting wonderfully to his environment and providing endless entertainment and joy. With his sleek, soft fur and expressive eyes, Sir Hops-A-Lot is not only playful but also incredibly affectionate, enjoying snuggles as much as his playful escapades. He’s seeking a home that can offer him a safe and nurturing space to explore and a loving family that delights in his cheerful antics. If you’re ready to add some lively fun and loving companionship to your life, Sir Hops-A-Lot could be your perfect match!');

COMMIT TRANSACTION;
